version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5439:5439'
    networks:
      - local-keycloak
    volumes:
      - db:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_PASSWORD: 1234
      KC_DB_USERNAME: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - '8082:8080'
    restart: unless-stopped
    networks:
      - local-keycloak

  ms-discovery:
    container_name: ms_discovery
    build:
      context: ./ms-discovery
      target: development
    ports:
      - '8761:8761'
    restart: unless-stopped
    networks:
      - local-microservices

  ms-gateway:
    container_name: ms_gateway
    build:
      context: ./ms-gateway
      target: development
    ports:
      - '8090:8090'
    restart: unless-stopped
    networks:
      - local-microservices

networks:
  local-keycloak:
  local-microservices:

volumes:
  db: