#Configuraciones del server
server:
  port: 8090

#Configuraciones de Eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true

#Configuraciones de Spring Cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
        - id: ms-movies
          uri: lb://ms-movies
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=2
      default-filters:
        - TokenRelay
        #- RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: onpHL21FsAXbZ3LhmOBjN2rjjeRKELQ4
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
            jwk-set-uri: http://localhost:8082/realms/DigitalMedia/protocol/openid-connect/certs