#Configuraciones del server
server:
  port: 8090

#Configuraciones de Eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#Configuraciones de Spring Cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - StripPrefix=2
      default-filters:
        - TokenRelay
        #- RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          digital-media:
            client-id: api-gateway
            client-secret: 81AFbdfX1rMvob1qeZgDyfOxwxkUNjzp
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/DigitalMedia
        provider:
          digital-media:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
            jwk-set-uri: http://localhost:8082/realms/DigitalMedia/protocol/openid-connect/certs