#Configuraciones de Spring Cloud
spring:
  application:
    name: ms-eureka-server

#Configuraciones del server
server:
  port: 8761

#Configuraciones de Eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#Configuraciones para actuator
management:
  endpoints:
    web:
      exposure:
        include: serviceregistry, health, info
  info:
    env:
      enabled: true

info:
  app:
    name: ms-discovery
    description: Eureka server
    version: 1.0.0